// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: protos/common/greeting.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGreetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGreetingRequest) Reset() {
	*x = GetGreetingRequest{}
	mi := &file_protos_common_greeting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetingRequest) ProtoMessage() {}

func (x *GetGreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_greeting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetingRequest.ProtoReflect.Descriptor instead.
func (*GetGreetingRequest) Descriptor() ([]byte, []int) {
	return file_protos_common_greeting_proto_rawDescGZIP(), []int{0}
}

func (x *GetGreetingRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGreetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGreetingResponse) Reset() {
	*x = GetGreetingResponse{}
	mi := &file_protos_common_greeting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGreetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGreetingResponse) ProtoMessage() {}

func (x *GetGreetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_greeting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGreetingResponse.ProtoReflect.Descriptor instead.
func (*GetGreetingResponse) Descriptor() ([]byte, []int) {
	return file_protos_common_greeting_proto_rawDescGZIP(), []int{1}
}

func (x *GetGreetingResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_protos_common_greeting_proto protoreflect.FileDescriptor

const file_protos_common_greeting_proto_rawDesc = "" +
	"\n" +
	"\x1cprotos/common/greeting.proto\x12\x06common\"$\n" +
	"\x12GetGreetingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"1\n" +
	"\x13GetGreetingResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting2Y\n" +
	"\x0fGreetingService\x12F\n" +
	"\vGetGreeting\x12\x1a.common.GetGreetingRequest\x1a\x1b.common.GetGreetingResponseB,Z*github.com/rootrl/grpc-hello/protos/commonb\x06proto3"

var (
	file_protos_common_greeting_proto_rawDescOnce sync.Once
	file_protos_common_greeting_proto_rawDescData []byte
)

func file_protos_common_greeting_proto_rawDescGZIP() []byte {
	file_protos_common_greeting_proto_rawDescOnce.Do(func() {
		file_protos_common_greeting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_common_greeting_proto_rawDesc), len(file_protos_common_greeting_proto_rawDesc)))
	})
	return file_protos_common_greeting_proto_rawDescData
}

var file_protos_common_greeting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_common_greeting_proto_goTypes = []any{
	(*GetGreetingRequest)(nil),  // 0: common.GetGreetingRequest
	(*GetGreetingResponse)(nil), // 1: common.GetGreetingResponse
}
var file_protos_common_greeting_proto_depIdxs = []int32{
	0, // 0: common.GreetingService.GetGreeting:input_type -> common.GetGreetingRequest
	1, // 1: common.GreetingService.GetGreeting:output_type -> common.GetGreetingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_common_greeting_proto_init() }
func file_protos_common_greeting_proto_init() {
	if File_protos_common_greeting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_common_greeting_proto_rawDesc), len(file_protos_common_greeting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_common_greeting_proto_goTypes,
		DependencyIndexes: file_protos_common_greeting_proto_depIdxs,
		MessageInfos:      file_protos_common_greeting_proto_msgTypes,
	}.Build()
	File_protos_common_greeting_proto = out.File
	file_protos_common_greeting_proto_goTypes = nil
	file_protos_common_greeting_proto_depIdxs = nil
}
